### ISSUE TITLE
VCS database workflow

### ISSUE THREAD

**Issue by itsDrac** [shubhexists/vault#12]
Hi this is a continuation of #11 

This is what I have as a VCS database for vault using `yaml` as a config file.

```(rust)
.vault/
    | master/
        | ...
    | init.ymal
```

```(yaml)
# .vault/init.ymal

Current branch: master 

Branches:
- master
- new_branch

```

```(sh)
master/
    | config.ymal
    | tb3a1/
    | w1we4/
```

```
# master/config.ymal
head: tb3a1

commits:
    tb3a1: Commit massage 1
    w1we4: Commit massage 2
    
hashs:
    tb3a1: tb3a1529fdan39rmi420fdnsd840dgn428803nf9
    w1we4: w1we4jgsdi3l498w38gnw90295bg90w94hti9
    
```

*TODO*: How are going to store files and folders, inside `master/tb3a1` folder.
